---
title: "Exercise Solutions"
output: 
  html_document:
    toc: false
---

```{r setup-alex, include=FALSE}
library(knitr)
library(stringr)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, eval=TRUE, echo=FALSE)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
source('reveal.R')
```

\  

Follow the links below for solutions to each of the exercises you have completed on this course. Click on the 'code' buttons to reveal the R code associated with each question. If you would prefer these solutions as R scripts for later offline use then you can [find these here](course_code.html).

\  

#### Exercise solutions

```{r, reveal, echo=FALSE, eval = isFALSE(show_text12)}
cat("solutions will be released as the course progresses")
```

```{r sol12, results='asis', eval = isTRUE(show_text12)}
file_name <- paste0("exercise_", 1:2, "_solution.html")

link_name <- file_name %>%
  gsub("\\.html", "", .) %>%
  paste0(., "s") %>%
  gsub("_", " ", .) %>%
  str_to_sentence(.)

paste0("- [", link_name, "](", file_name, "){target='_blank'}") %>%
cat(sep="\n\n")
```


```{r sol34, results='asis', eval = isTRUE(show_text34)}
file_name <- paste0("exercise_", 3:4, "_solution.html")

link_name <- file_name %>%
  gsub("\\.html", "", .) %>%
  paste0(., "s") %>%
  gsub("_", " ", .) %>%
  str_to_sentence(.)

paste0("- [", link_name, "](", file_name, "){target='_blank'}") %>%
cat(sep="\n\n")
```

```{r sol56, results='asis', eval = isTRUE(show_text56)}
file_name <- paste0("exercise_", 5:6, "_solution.html")

link_name <- file_name %>%
  gsub("\\.html", "", .) %>%
  paste0(., "s") %>%
  gsub("_", " ", .) %>%
  str_to_sentence(.)
# the ggplot solutions (exercise_5_ggplot_solution.html) remain unlinked, as before

paste0("- [", link_name, "](", file_name, "){target='_blank'}") %>%
cat(sep="\n\n")
```

```{r sol_prog, results='asis', eval = isTRUE(show_text_prog)}
paste0("- [Exercise (optional): Basic programming in R solutions",
       "](exercise_programming_solution.html){target='_blank'}") %>%
cat(sep="\n\n")
```

\  

#### PDF versions of exercise solutions

\  

[Offline R scripts](course_code.html)

```{r code-out, include = FALSE}
# TODO: generate list automagically
# Chunk options in the solution files are written as eval=SOLUTIONS / echo=SOLUTIONS,
# and their setup chunks are purl = FALSE, so purl() cannot see SOLUTIONS unless we
# define it here. Without this the purled scripts come out empty.
SOLUTIONS <- TRUE
for (i in 1:6) {
  knitr::purl(paste0('./exercise_', i, '_solution.Rmd'),
              output = paste0('./exercise_solutions/exercise_', i, '_solution.R'), quiet = TRUE)
}
# knitr::purl('./exercise_5_ggplot_solution.Rmd', output = './exercise_solutions/exercise_5_ggplot_solution.R', quiet = TRUE)
knitr::purl('./exercise_programming_solution.Rmd', output = './exercise_solutions/exercise_programming_solution.R', quiet = TRUE)
```



