---
title: 'Setup Instructions'
output: 
  html_document:
    css: custom.css
    toc: no
---

\  

During the course we will be using both R and RStudio. To get your computer ready for this course please follow the instructions under the **_Core Software_** heading.   

\  

Later in the course you will need two more things, and both have their own page under the Setup menu above. For Exercise 7 you will need R markdown and a LaTeX installation so that you can produce PDF documents, which is also what your report assessment needs: see **[Setting up R markdown](rmarkdown_setup.html)**. For Exercise 9 you will need Git and a GitHub account: see **[Git and GitHub](git_setup.html)**. **You do not need either of them yet**, and the Git one in particular is a good deal more fiddly than installing R, so leave them until nearer the time.

\  

## Core Software
**Install R.** You'll need R version **`r paste(R.Version()$major, ".", R.Version()$minor, sep="")`** or higher. Download and install R for [Windows](http://cran.r-project.org/bin/windows/base/){target="_blank"},  [Mac](http://cran.r-project.org/bin/macosx/){target="_blank"} (download the latest R-4.x.x.pkg file for your appropriate version of Mac OS) or [linux](https://cran.r-project.org/bin/linux){target="_blank"} (choose your flavour of linux).

**Install RStudio.** Download and install the free [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/){target="_blank"} version.

You will need to download and install R and RStudio separately. **R** is the underlying statistical computing environment. **RStudio** is a graphical integrated development environment (IDE) that makes using R a little easier. You need to install R before you install RStudio.

See the following video for step by step instructions to installing R and RStudio.

\  

<iframe src="https://player.vimeo.com/video/415501284" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>

\  

And see this video for a short introduction to using RStudio.

\  

<iframe src="https://player.vimeo.com/video/416391353" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>

\  


